openapi: 3.0.0
info:
  title: GTIN Owner OpenAPI
  version: 4.0.0-rc5
  description: OpenAPI for GTIN owner information
servers:
  - url: http://127.0.0.1:8080
    description: local.epi
paths:
  "/gtinOwner/{epiDomain}/{gtin}":
    get:
      summary: Retrieve the owner domain of a GTIN
      description: Returns the DSU domain where the GTIN is anchored
      tags:
        - GTIN Owner
      parameters:
        - name: epiDomain
          in: path
          description: EPI domain where the GTIN is registered
          required: true
          schema:
            type: string
            example: local.epi
        - name: gtin
          in: path
          description: GTIN number (14 digits)
          required: true
          schema:
            type: string
            pattern: ^\d{14}$
      responses:
        "200":
          description: Successfully retrieved owner domain
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GtinOwnerResponse"
              example:
                domain: local.epi
        "400":
          description: Domain validation failed
          content:
            text/plain:
              schema:
                type: string
                example: Fail
        "404":
          description: GTIN not found
          content:
            text/plain:
              schema:
                type: string
                example: ""
        "500":
          description: Error processing request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "529":
          description: Server busy processing request
          content:
            text/plain:
              schema:
                type: string
                example: Server busy finding gtinOwner
  "/gtinOwner/{epiDomain}/{gtin}/{subdomain}":
    get:
      summary: Internal GTIN Owner redirection endpoint
      description: Internal endpoint that handles subdomain redirection (backward
        compatibility)
      tags:
        - GTIN Owner
      parameters:
        - name: epiDomain
          in: path
          description: EPI domain where the GTIN is registered
          required: true
          schema:
            type: string
            example: local.epi
        - name: gtin
          in: path
          description: GTIN number (14 digits)
          required: true
          schema:
            type: string
            pattern: ^\d{14}$
        - name: subdomain
          in: path
          description: EPI subdomain (for compatibility)
          required: true
          schema:
            type: string
            example: sub
      responses:
        "200":
          description: Successfully retrieved owner domain
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GtinOwnerResponse"
              example:
                domain: local.epi
        "400":
          description: Domain validation failed
          content:
            text/plain:
              schema:
                type: string
                example: Fail
        "404":
          description: GTIN not found
          content:
            text/plain:
              schema:
                type: string
                example: ""
        "500":
          description: Error processing request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "529":
          description: Server busy processing request
          content:
            text/plain:
              schema:
                type: string
                example: Server busy finding gtinOwner
components:
  schemas:
    GtinOwnerResponse:
      type: object
      properties:
        domain:
          type: string
          description: The domain that owns the GTIN
          example: local.epi
      required:
        - domain
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: Failed to get last version for SSI
tags:
  - name: GTIN Owner
    description: GTIN ownership information
