name: Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Check out epi-workspace repo'
        uses: actions/checkout@v4.1.3
        with:
          repository: axiologic-pla/epi-workspace
          path: "./epi-workspace"
          ref: master
          
      - name: 'Run dev install for epi-workspace'
        run: cd epi-workspace && npm run dev-install
        env:
          GITHUB_ORGANIZATION: 'axiologic-pla'

      - name: 'Commit files'
        run: |
          rm -rf `find ./epi-workspace -type d -name .git`
          rm -rf `find ./epi-workspace -name .gitignore`
          git add -A .
          git config --local user.email "psk.build.track@gmail.com"
          git config --local user.name "devteam[bot]"
          git commit -a -m "Code base updates"
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      
      
